Expand diagnostic function -- send a key and check result. Check /system/bin/getprop and added troubleshooting tips

diff --git a/android-pin-bruteforce b/android-pin-bruteforce
--- a/android-pin-bruteforce
+++ b/android-pin-bruteforce
@@ -102,7 +102,27 @@ function diagnostic_info() {
     log_fail "Device not found"
   fi
 
-  echo "Tip: Try powering off the phone and taking out the battery"
+  log_info "Sending Enter Key"
+  echo enter | $HID_KEYBOARD $KEYBOARD_DEVICE keyboard
+  RET=$?
+
+  if [ $RET -eq 0 ]; then
+    log_pass "Key was sent succeessfully."
+  else
+    log_fail "Key failed to send. Return code $RET."
+  fi
+
+  log_info "Executing Command: /system/bin/getprop |grep usb"
+  /system/bin/getprop |grep usb
+  RET=$?
+
+  echo  
+
+  log_info "Troubleshooting tips"
+  echo "- Nethunter HID support can be a PITA."
+  echo "- Try powering off the phone and taking out the battery"
+  echo "- Try /system/bin/setprop sys.usb.config hid"
+  echo "- Try it on your PC or laptop"
   echo
   exit
 }
